function nanf() { //THIS FUNCTION WILL DISPLAY "NaN" BECAUSE 0/0 IS NOT A NUMBER
    document.getElementById("Test").innerHTML = 0/0;
}

function isnan1() { //THIS FUNCTION WILL DISPLAY "TRUE" BECAUSE "GARRETT" IS NOT A NUMBER
    document.getElementById("Test2").innerHTML = isNaN('Garrett');
}

function isnan2() { //THIS FUNCTION WILL DISPLAY "FALSE" BECAUSE "767" IS A NUMBER
    document.getElementById("Test3").innerHTML = isNaN('767');
}

function inf() { //THIS FUNCTION WILL DISPLAY "INFINITY" BECAUSE THE NUMBER IS LARGER THAN 1.7976931348623157E308
    document.getElementById("Test4").innerHTML = (2E310);
}

function neginf() { //THIS FUNCTION WILL DISPLAY "-INFINITY" BECAUSE THE NUMBER IS A LOWER NEGATIVE NUMBER THAN 1.7976931348623157E308
    document.getElementById("Test5").innerHTML = (-3E310);
}

document.write(typeof "Garrett"); //THIS WILL DISPLAY "STRING" IN THE BROWSER BECAUSE "GARRETT" IS A TYPE OF "STRING"

document.write(typeof 777); //THIS WILL DISPLAY "NUMBER" IN THE BROWSER BECAUSE "777" IS A NUMBER

document.write("77" + 9); //THIS EXPRESSION COMBINES BOTH A STRING AND A NUMBER TOGETHER, THERFORE IN THE BROWSER IT WILL DISPLAY AS "779" 

document.write(10 > 2); //THIS WILL DISPLAY "TRUE" IN THE BROWSER (10 IS GREATER THAN 2)

document.write(10 < 2); //THIS WILL DISPLAY "FALSE" IN THE BROWSER (10 IS NOT LESS THAN 2)

document.write(10 == 10); //THIS WILL DISPLAY "TRUE" IN THE BROWSER ("==" IS USED TO CHECK FOR EQUALITY)

document.write(3 == 11); //THIS WILL DISPLAY "FALSE" IN THE BROWSER

X = 20; //CREATED TWO VARIABLES 
Y = 20; //(===) IS USED TO CHECK IF BOTH ARE EQUAL TO ONE ANOTHER AND ARE THE SAME TYPE OF DATA
document.write(X === Y); //THIS DISPLAYS "TRUE" BECAUSE BOTH X AND Y ARE EQUAL TO ONE ANOTHER AND THEY ARE THE SAME TYPE OF DATA

A = 21;
B = "47";
document.write(A === B); //THIS DISPLAYS "FALSE" BECAUSE THEY ARE NOT EQUAL TO ONE ANOTHER AND THEY ARE TWO DIFFERENT TYPES OF DATA

G = 56;
H = "56";
document.write(G === H); //THIS DISPLAYS AS "FALSE" BECAUSE EVEN THOUGH THEY ARE BOTH EQUAL TO ONE ANOTHER, THEY ARE NOT THE SAME TYPE OF DATA

C = 82;
D = "Dog";
document.write(C === D); //THIS DISPLAYS AS "FALSE" BECAUSE THEY ARE NOT THE SAME TYPE OF DATA AT ALL

document.write(10 > 2 && 20 < 30); //THIS DISPLAYS TRUE BECAUSE BOTH ARE TRUE (&& IS USED TO CHECK IF TWO OR MORE VALUES ARE TRUE) [&& means "AND"]

document.write(30 > 40) && (20 > 22); //THIS DISPLAYS AS FALSE BECAUSE NEITHER IS A TRUE STATEMENT

document.write(22 > 21) || (99 < 1); //THIS DISPLAYS AS TRUE BECAUSE ONE IS TRUE AND WE ARE USING (||) WHICH MEANS "OR" SO ONLY ONE NEEDS TO BE TRUE TO DISPLAY "TRUE"

document.write(33 > 66) || (2 < 1); //THIS DISPLAYS AS FALSE BECAUSE NEITHER ONE IS TRUE

function notf1() { //(!) IS USED AS THE (NOT) OPERATOR. THIS CHECKS WHETHER OR NOT SOMETHING IS TRUE. IF IT IS TRUE IT WILL BE DISPLAYED AS "FALSE", IF IT IS FALSE IT WILL BE DISPLAYED AS "TRUE"
    document.getElementById("Not1").innerHTML = !(20 > 10); //THIS FUNCTION WILL DISPLAY "FALSE"
}

function notf2() { //THIS FUNCTION WILL DISPLAY "TRUE"
    document.getElementById("Not2").innerHTML = !(30 > 50);
}
